version: "2"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      # Plain DNS
      - 53:53/tcp
      - 53:53/udp
      # DHCP
      - 67:67/udp
      - 68:68/tcp
      - 68:68/udp
      # Admin panel, HTTPS/DNS-over-HTTPS
      - 80:80
      - 3000:3000/tcp
      - 443:443/tcp
      - 443:443/udp
      # DNS-over-TLS
      # - 853:853/tcp
      # DNS-over-QUIC
      # - 784:784/udp
      # - 853:853/udp
      # - 8853:8853/udp
      # DNSCrypt
      # - 5443:5443/udp
    volumes:
      - ${DOCKER_DATA}/adguardhome/work:/opt/adguardhome/work
      - ${DOCKER_DATA}/adguardhome/conf:/opt/adguardhome/conf
    restart: unless-stopped
